[DEBUG] [control] compile src
[DEBUG] [compile] Sources compiled - modules: 1, scripts: 1
[DEBUG] [compile] Results committed
[DEBUG] [control] push -e
[DEBUG] [control] execute -s 0xA -v 0u64 --dry-run
[DEBUG] [execute] Script executed - changes: 1, events: 0
[DEBUG] [control] execute -s 0xA -v 0u64
[DEBUG] [execute] Script executed - changes: 1, events: 0
[DEBUG] [execute] Results committed
[DEBUG] [control] -F execute -s 0xA -v 0u64 --dry-run
VMError with status RESOURCE_ALREADY_EXISTS at location Module ModuleId { address: 00000000000000000000000000000042, name: Identifier("M") } at code offset 5 in function definition 0
[DEBUG] [control] [x] Script execution failed
[DEBUG] [control] -F execute -s 0xA -v 0u64
VMError with status RESOURCE_ALREADY_EXISTS at location Module ModuleId { address: 00000000000000000000000000000042, name: Identifier("M") } at code offset 5 in function definition 0
[DEBUG] [control] [x] Script execution failed
[DEBUG] [control] pop -e
[DEBUG] [control] execute -s 0xA -v 1u64 --dry-run
[DEBUG] [execute] Script executed - changes: 1, events: 0
[DEBUG] [control] execute -s 0xA -v 1u64
[DEBUG] [execute] Script executed - changes: 1, events: 0
[DEBUG] [execute] Results committed
